#!/usr/bin/env ruby

require 'thor'
require 'twitter'
require 'yaml'

class TwitterCLI < Thor

  desc "post TWEET", "post to your twitter with TWEET"
  def post(tweet)
    # tweet posting logic goes here
    client = read_config
    client.update(tweet)
    puts "#{Time.now} Posted: #{tweet}"
  end

  private

  def read_config
    access_tokens = YAML.load_file('access_tokens.yml')
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = access_tokens['consumer_api_key']
      config.consumer_secret     = access_tokens['consumer_api_secret']
      config.access_token        = access_tokens['access_token']
      config.access_token_secret = access_tokens['access_token_secret']
    end
    return client
  end
end

TwitterCLI.start(ARGV)
